name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: Add .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN?}" > .npmrc
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: cd packages/core && pnpm run test
      - name: Run build
        run: cd packages/core && pnpm run build
      - name: Get version
        run: |
          echo "::set-output name=version::$(cat packages/core/package.json | grep version | awk -F: '{ print $2 }' | sed 's/[", ]//g')"
        id: version
      - name: Create package
        run: |
          echo "::set-output name=package::$(./scripts/create-package.sh ${GITHUB_WORKSPACE} ${{ steps.version.outputs.version }})"
        id: package
      - name: Create changelog
        run: cd packages/core && pnpm run generate-changelog
      - name: release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: packages/core/CHANGELOG.md
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.package.outputs.package }}
          asset_name: bowser-jr-${{ steps.version.outputs.version }}.zip
          asset_content_type: application/gzip

